"""empty message

Revision ID: 7f454ee9dd60
Revises: 6098f62b9d47
Create Date: 2023-09-01 07:23:46.292039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f454ee9dd60'
down_revision = '6098f62b9d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('web_site')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_site', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###
